name: Wyze Sense 2 MQTT
version: "1.0.12"
slug: wyzesense2mqtt
description: Integrates Wyze Sense sensors with Home Assistant via MQTT, supporting sensor pairing, removal, climate data, and automatic device discovery using the raetha Docker image.
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
devices:
  - /dev/hidraw0
map:
  - path: /app/config
    read_only: false
    type: config
options:
  mqtt_host: 
  mqtt_username: ""
  mqtt_password: ""
  mqtt_client_id: wyzesense2mqtt
  self_topic_root: wyzesense2mqtt
  hass_topic_root: homeassistant
  usb_dongle: auto
  sensors_config: ""
  mqtt_port: 1883
  mqtt_clean_session: false
  mqtt_keepalive: 60
  mqtt_qos: 2
  mqtt_retain: true
  hass_discovery: true
  publish_sensor_name: true
  # UI groups for Home Assistant (supported in newer versions)
  # Basic MQTT settings
  # Advanced MQTT and sensor settings
ui:
  group:
    - name: "MQTT Settings"
      options:
        - mqtt_host
        - mqtt_username
        - mqtt_password
    - name: "Advanced MQTT"
      options:
        - mqtt_port
        - mqtt_client_id
        - mqtt_clean_session
        - mqtt_keepalive
        - mqtt_qos
        - mqtt_retain
        - self_topic_root
        - hass_topic_root
        - hass_discovery
        - publish_sensor_name
    - name: "Sensor Settings"
      options:
        - usb_dongle
        - sensors_config
schema:
  mqtt_host: str
  mqtt_username: str
  mqtt_password: str
  mqtt_client_id: str
  self_topic_root: str
  hass_topic_root: str
  usb_dongle: str
  sensors_config: str
  mqtt_port: int
  mqtt_clean_session: bool
  mqtt_keepalive: int
  mqtt_qos: int
  mqtt_retain: bool
  hass_discovery: bool
  publish_sensor_name: bool




