arch:
- aarch64
- amd64
- armv7
description: Configurable WyzeSense to MQTT Gateway for Home Assistant
host_network: true
image: raetha/wyzesense2mqtt:devel
init: false
map:
- path: /wyzesense2mqtt
  read_only: false
  type: addon_config
name: WyzeSense2MQTT
slug: wyzesense2mqtt
url: https://hub.docker.com/r/raetha/wyzesense2mqtt
version: '2025-08-2'
options:
  mqtt_host: ''
  mqtt_port: 1883
  mqtt_username: ''
  mqtt_password: ''
  mqtt_client_id: wyzesense2mqtt
  mqtt_clean_session: false
  mqtt_keepalive: 60
  mqtt_qos: 2
  mqtt_retain: true
  self_topic_root: wyzesense2mqtt
  hass_topic_root: homeassistant
  hass_discovery: true
  publish_sensor_name: true
  usb_dongle: auto